-- Beauty BI Dataset V2
-- Schema Version: beauty_bi_schema_v2_0
-- Target PostgreSQL Schema: beauty_bi_v2
--
-- Safety:
-- Only create or modify objects under beauty_bi_v2.
-- Never modify or truncate objects under public.

CREATE SCHEMA IF NOT EXISTS beauty_bi_v2;


CREATE TABLE IF NOT EXISTS beauty_bi_v2.dim_date (
    date_key INTEGER PRIMARY KEY,
    full_date DATE NOT NULL UNIQUE,

    year SMALLINT NOT NULL,
    quarter SMALLINT NOT NULL,
    month SMALLINT NOT NULL,
    month_name VARCHAR(20) NOT NULL,
    week_of_year SMALLINT NOT NULL,
    day_of_month SMALLINT NOT NULL,
    day_of_week SMALLINT NOT NULL,

    is_weekend BOOLEAN NOT NULL,
    is_holiday BOOLEAN NOT NULL DEFAULT FALSE,
    holiday_name VARCHAR(100),

    CHECK (quarter BETWEEN 1 AND 4),
    CHECK (month BETWEEN 1 AND 12),
    CHECK (week_of_year BETWEEN 1 AND 53),
    CHECK (day_of_month BETWEEN 1 AND 31),
    CHECK (day_of_week BETWEEN 1 AND 7),
    CHECK (is_holiday OR holiday_name IS NULL)
);


CREATE TABLE IF NOT EXISTS beauty_bi_v2.dim_region (
    region_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    region_code VARCHAR(50) NOT NULL UNIQUE,
    region_name VARCHAR(100) NOT NULL,
    province_name VARCHAR(100) NOT NULL,
    region_group VARCHAR(50) NOT NULL,
    city_tier VARCHAR(50) NOT NULL,

    CHECK (BTRIM(region_code) <> ''),
    CHECK (BTRIM(region_name) <> ''),
    CHECK (BTRIM(province_name) <> ''),
    CHECK (BTRIM(region_group) <> ''),
    CHECK (BTRIM(city_tier) <> '')
);


CREATE TABLE IF NOT EXISTS beauty_bi_v2.dim_channel (
    channel_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    channel_code VARCHAR(50) NOT NULL UNIQUE,
    channel_name VARCHAR(100) NOT NULL UNIQUE,
    channel_type VARCHAR(50) NOT NULL,

    is_sales_channel BOOLEAN NOT NULL,
    is_marketing_channel BOOLEAN NOT NULL,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,


    CHECK (BTRIM(channel_code) <> ''),
    CHECK (BTRIM(channel_name) <> ''),
    CHECK (BTRIM(channel_type) <> ''),
    CHECK (is_sales_channel OR is_marketing_channel)
);


CREATE TABLE IF NOT EXISTS beauty_bi_v2.dim_product (
    product_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    sku_code VARCHAR(50) NOT NULL UNIQUE,
    product_name VARCHAR(200) NOT NULL,
    brand VARCHAR(100) NOT NULL,
    category VARCHAR(100) NOT NULL,
    subcategory VARCHAR(100) NOT NULL,

    list_price NUMERIC(12, 2) NOT NULL,
    launch_date DATE NOT NULL,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,

    CONSTRAINT ck_dim_product_sku_code_not_blank
        CHECK (BTRIM(sku_code) <> ''),

    CONSTRAINT ck_dim_product_product_name_not_blank
        CHECK (BTRIM(product_name) <> ''),

    CONSTRAINT ck_dim_product_brand_not_blank
        CHECK (BTRIM(brand) <> ''),

    CONSTRAINT ck_dim_product_category_not_blank
        CHECK (BTRIM(category) <> ''),

    CONSTRAINT ck_dim_product_subcategory_not_blank
        CHECK (BTRIM(subcategory) <> ''),

    CONSTRAINT ck_dim_product_list_price_positive
        CHECK (list_price > 0)
);


CREATE TABLE IF NOT EXISTS beauty_bi_v2.dim_campaign (
    campaign_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    campaign_code VARCHAR(50) NOT NULL UNIQUE,
    campaign_family VARCHAR(50) NOT NULL,
    campaign_name VARCHAR(200) NOT NULL,
    campaign_type VARCHAR(50) NOT NULL,

    start_date DATE NOT NULL,
    end_date DATE NOT NULL,
    status_cutoff TIMESTAMP NOT NULL,

    objective VARCHAR(100) NOT NULL,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,

    CONSTRAINT ck_dim_campaign_code_not_blank
        CHECK (BTRIM(campaign_code) <> ''),

    CONSTRAINT ck_dim_campaign_family_not_blank
        CHECK (BTRIM(campaign_family) <> ''),

    CONSTRAINT ck_dim_campaign_name_not_blank
        CHECK (BTRIM(campaign_name) <> ''),

    CONSTRAINT ck_dim_campaign_type_not_blank
        CHECK (BTRIM(campaign_type) <> ''),

    CONSTRAINT ck_dim_campaign_objective_not_blank
        CHECK (BTRIM(objective) <> ''),

    CONSTRAINT ck_dim_campaign_date_order
        CHECK (end_date >= start_date),

    CONSTRAINT ck_dim_campaign_status_cutoff
        CHECK (status_cutoff < start_date::timestamp)
);


CREATE TABLE IF NOT EXISTS beauty_bi_v2.dim_promotion (
    promotion_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    promotion_code VARCHAR(50) NOT NULL UNIQUE,
    promotion_name VARCHAR(200) NOT NULL,
    promotion_type VARCHAR(50) NOT NULL,

    discount_rate NUMERIC(5, 4),

    start_date DATE NOT NULL,
    end_date DATE NOT NULL,

    target_member_level VARCHAR(50),
    is_active BOOLEAN NOT NULL DEFAULT TRUE,

    CONSTRAINT ck_dim_promotion_code_not_blank
        CHECK (BTRIM(promotion_code) <> ''),

    CONSTRAINT ck_dim_promotion_name_not_blank
        CHECK (BTRIM(promotion_name) <> ''),

    CONSTRAINT ck_dim_promotion_type_not_blank
        CHECK (BTRIM(promotion_type) <> ''),

    CONSTRAINT ck_dim_promotion_date_order
        CHECK (end_date >= start_date),

    CONSTRAINT ck_dim_promotion_discount_rate
        CHECK (discount_rate IS NULL OR (discount_rate > 0 AND discount_rate < 1)),

    CONSTRAINT ck_dim_promotion_target_level
        CHECK (target_member_level IS NULL OR BTRIM(target_member_level) <> '')
);


CREATE TABLE IF NOT EXISTS beauty_bi_v2.dim_customer (
    customer_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    customer_code VARCHAR(50) NOT NULL UNIQUE,
    first_seen_date DATE NOT NULL,

    home_region_id BIGINT NOT NULL
        REFERENCES beauty_bi_v2.dim_region(region_id),

    customer_status VARCHAR(50) NOT NULL,

    CONSTRAINT ck_dim_customer_code_not_blank
        CHECK (BTRIM(customer_code) <> ''),

    CONSTRAINT ck_dim_customer_status_not_blank
        CHECK (BTRIM(customer_status) <> '')
);


CREATE TABLE IF NOT EXISTS beauty_bi_v2.dim_membership_account (
    membership_account_id BIGINT
        GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    member_code VARCHAR(50) NOT NULL UNIQUE,
    joined_at TIMESTAMP NOT NULL,

    join_channel_id BIGINT NOT NULL
        REFERENCES beauty_bi_v2.dim_channel(channel_id),

    membership_status VARCHAR(50) NOT NULL,

    CONSTRAINT ck_dim_membership_account_code_not_blank
        CHECK (BTRIM(member_code) <> ''),

    CONSTRAINT ck_dim_membership_account_status_not_blank
        CHECK (BTRIM(membership_status) <> '')
);


CREATE TABLE IF NOT EXISTS beauty_bi_v2.bridge_customer_membership (
    customer_membership_id BIGINT
        GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    customer_id BIGINT NOT NULL
        REFERENCES beauty_bi_v2.dim_customer(customer_id),

    membership_account_id BIGINT NOT NULL
        REFERENCES beauty_bi_v2.dim_membership_account(
            membership_account_id
        ),

    effective_from_ts TIMESTAMP NOT NULL,
    effective_to_ts TIMESTAMP,

    mapping_status VARCHAR(50) NOT NULL,

    CONSTRAINT ck_bridge_customer_membership_status_not_blank
        CHECK (BTRIM(mapping_status) <> ''),

    CONSTRAINT ck_bridge_customer_membership_interval
        CHECK (
            effective_to_ts IS NULL
            OR effective_to_ts > effective_from_ts                             
        ),

    -- 同一 customer、会员账户和开始时间不能重复
    CONSTRAINT uq_bridge_customer_membership_start
        UNIQUE (
            customer_id,
            membership_account_id,
            effective_from_ts
        )
);


-- 当前有效关系中，一个 customer 最多对应一个会员账户
CREATE UNIQUE INDEX IF NOT EXISTS
    uq_bridge_customer_membership_open_customer
ON beauty_bi_v2.bridge_customer_membership (customer_id)
WHERE effective_to_ts IS NULL;


-- 当前有效关系中，一个会员账户最多对应一个 customer
CREATE UNIQUE INDEX IF NOT EXISTS
    uq_bridge_customer_membership_open_account
ON beauty_bi_v2.bridge_customer_membership (membership_account_id)
WHERE effective_to_ts IS NULL;


CREATE TABLE IF NOT EXISTS
    beauty_bi_v2.fact_membership_channel_binding_history (
    binding_history_id BIGINT
        GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    membership_account_id BIGINT NOT NULL
        REFERENCES beauty_bi_v2.dim_membership_account(
            membership_account_id
        ),

    channel_id BIGINT NOT NULL
        REFERENCES beauty_bi_v2.dim_channel(channel_id),

    effective_from_ts TIMESTAMP NOT NULL,
    effective_to_ts TIMESTAMP,

    binding_status VARCHAR(50) NOT NULL,
    binding_source VARCHAR(50) NOT NULL,

    CONSTRAINT ck_membership_binding_status_not_blank
        CHECK (BTRIM(binding_status) <> ''),

    CONSTRAINT ck_membership_binding_source_not_blank
        CHECK (BTRIM(binding_source) <> ''),

    CONSTRAINT ck_membership_binding_interval
        CHECK (
            effective_to_ts IS NULL
            OR effective_to_ts > effective_from_ts
        ),

    -- 同一会员、渠道和开始时间不能重复
    CONSTRAINT uq_membership_binding_start
        UNIQUE (
            membership_account_id,
            channel_id,
            effective_from_ts
        )
);


CREATE UNIQUE INDEX IF NOT EXISTS
    uq_membership_binding_open_account_channel
ON beauty_bi_v2.fact_membership_channel_binding_history (
    membership_account_id,
    channel_id
)
WHERE effective_to_ts IS NULL;


CREATE TABLE IF NOT EXISTS
    beauty_bi_v2.fact_membership_tier_history (
    tier_history_id BIGINT
        GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    membership_account_id BIGINT NOT NULL
        REFERENCES beauty_bi_v2.dim_membership_account(
            membership_account_id
        ),

    member_level VARCHAR(50) NOT NULL,

    effective_from_ts TIMESTAMP NOT NULL,
    effective_to_ts TIMESTAMP,

    evaluated_at TIMESTAMP NOT NULL,
    r12_valid_spend NUMERIC(14, 2) NOT NULL,

    change_type VARCHAR(20) NOT NULL,

    CONSTRAINT ck_membership_tier_level_not_blank
        CHECK (BTRIM(member_level) <> ''),

    CONSTRAINT ck_membership_tier_interval
        CHECK (
            effective_to_ts IS NULL
            OR effective_to_ts > effective_from_ts
        ),

    CONSTRAINT ck_membership_tier_r12_spend_non_negative
        CHECK (r12_valid_spend >= 0),

    CONSTRAINT ck_membership_tier_change_type
        CHECK (
            change_type IN (
                'initial',
                'upgrade',
                'downgrade'
            )
        ),

    -- 同一会员账户不能在同一时刻开始两个等级区间
    CONSTRAINT uq_membership_tier_start
        UNIQUE (
            membership_account_id,
            effective_from_ts
        )
);


CREATE UNIQUE INDEX IF NOT EXISTS
    uq_membership_tier_open_account
ON beauty_bi_v2.fact_membership_tier_history (
    membership_account_id
)
WHERE effective_to_ts IS NULL;